### ISSUE TITLE
Details about the JWT_SECRET and GITHUB_TOKEN 

### ISSUE THREAD

**Issue by arunics** [auth0/repo-supervisor#13]
Probably I am missing something in the Document. 
Is GITHUB_TOKEN - Personal Access Token?
How and where the  JWT_SECRET set?

**Comment by radekk** [comment]
Hey @arunics,

`GITHUB_TOKEN` is your personal github token.
`JWT_SECRET` is just a random secret that is going to be used for building up URLs and passing the data. Generate a random string and just use it.

Hope it helps, let me know if it's still not clear then I will re-open this issue.
