### ISSUE TITLE
Issues building as a Docker container 

### ISSUE THREAD

**Issue by ThisIsMissEm** [auth0/repo-supervisor#19]
Hi, I'm not super familiar with Docker, but following your instructions, I'm getting the following errors, I'm not sure if it's a transient error or if it's actually something related to repo-supervisor — A quick google search didn't really help.

```
repo-supervisor $ docker build -t repo-supervisor .
Sending build context to Docker daemon  1.166MB
Step 1/11 : FROM golang:latest
 ---> 3858fd70eed2
Step 2/11 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 40458838ad07
Step 3/11 : RUN apt-get update -qq && apt-get install -y     locales     -qq
 ---> Running in 6136052d862e
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Package 'locales' has no installation candidate
The command '/bin/sh -c apt-get update -qq && apt-get install -y     locales     -qq' returned a non-zero code: 100
```

**Comment by radekk** [comment]
Hi,

Thank you for reporting this and sorry for the late answer. I did check and it's working fine on my end. I see that the `:latest` image for golang for me is `41e7847de71b` where in your logs it shows ` 3858fd70eed2`.

There could be some kind of issue with that specific image version. Please check it once again at let me know if it works.

**Comment by radekk** [comment]
I didn't receive any additional details on that. Closing issue for now. Feel free to reopen if it still doesn't work as expected.
