### ISSUE TITLE
Make docker image publicly available

### ISSUE THREAD

**Issue by hoto** [auth0/repo-supervisor#22]
Hi, the docker image for this repository does not exist on the docker hub.
The command from `README.md` to run a docker image requires you to clone the repository and build the image locally first.

Adding an automated build on docker hub can be done in two minutes and does not require any maintanance.

![image](https://user-images.githubusercontent.com/3105832/47737329-9045c080-dc68-11e8-80ed-85b72d7aa8d4.png)

Please consider :)
Andy

**Comment by hoto** [comment]
You can even see that someone already forked this repo and made an automated build on docker hub: https://hub.docker.com/r/amaysim/repo-supervisor/

**Comment by radekk** [comment]
We are not pushing images into our docker hub org right now. But that's something we might consider in the future so whenever it's back I will put additional comments/notes here.
