### ISSUE TITLE
AWS Lambda deployment

### ISSUE THREAD

**Issue by raybradley** [auth0/repo-supervisor#23]
I'm trying to deploy this onto AWS Lambda and having trouble. I'd be more than happy to author and contribute detailed docs on how to do this, but would benefit from at least a kick-start on how to accomplish it. The very beginning of the webtask.js file:

> module.exports

...seems to be problematic.

Ideas?

**Comment by caoimhinmacaoidh** [comment]
@raybradley If you ever got to producing that doc, I'd love to see it. I'm looking to get this into a lambda too

**Comment by radekk** [comment]
Hey 👋 I just wanted to let you know that we are working on the roadmap for this project and migrating to Lambda is on of our top priorities. I will update this ticket when roadmap is ready.

**Comment by raybradley** [comment]
Awesome, @radekk. Happy to test. @caoimhinmacaoidh, no I didn’t but it looks like the auth0 folks are on it.

**Comment by radekk** [comment]
@caoimhinmacaoidh @raybradley It's been a while but we finally support AWS Lambda in the v3.0.0 release 🎉 Feel free to test it out and provide a feedback if you have some time to give it a try.
