### ISSUE TITLE
Azure extension

### ISSUE THREAD

**Issue by SuryakiranAS** [auth0/repo-supervisor#31]
Hi Team,

We would to use this tool in our Azure DevOps pipelines, can you let us know how to integrate this tool in azure since this tool not available as an extension to install and use from azure marketplace.

**Comment by radekk** [comment]
Hi @SuryakiranAS,

Is it possible to run a docker image in your pipeline? This how it might look like:

- build docker image from this repository (`docker build -t repo-supervisor .`)
- upload it to your docker registry/artifactory so it's accessible from the pipeline
- add a new step to your CI (`docker run -it --rm -v /local/path/on/your/host:/opt/scan_me repo-supervisor /bin/bash -c "source ~/.bashrc && JSON_OUTPUT=1 node /opt/repo-supervisor/dist/cli.js /opt/scan_me"`)
- previous command mounts a volume to docker container `/local/path/on/your/host` which in your case would be a local path where application source is located, for pipeline execution it might required to run `pwd` command to get it
- after that it should return JSON response `{"result":[{"filepath":"./test/fixtures/integration/dir.with.secrets/foo/bar.js","secrets":["zJd-55qmsY6LD53CRTqnCr_g-","gm5yb-hJWRoS7ZJTi_YUj_tbU","GxC56B6x67anequGYNPsW_-TL","MLTk-BuGS8s6Tx9iK5zaL8a_W","2g877BA_TsE-WoPoWrjHah9ta"]},{"filepath":"./test/fixtures/integration/dir.with.secrets/foo/foo.json","secrets":["d7kyociU24P9hJ_sYVkqzo-kE","q28Wt3nAmLt_3NGpqi2qz-jQ7"]}]}`
- as the last step you would need to run bash command to parse the output i.e. using `jq` tool

Let me know if that helps. I don't have a prior experience with Azure extensions but that's something we might put on our radar in the future.
