### ISSUE TITLE
Does not work without webtask

### ISSUE THREAD

**Issue by stacifractals** [auth0/repo-supervisor#33]
Webtask is not accepting new accounts, therefore, without running wt init (impossible if you don't have an account) you cannot deploy this app? am I missing something obvious?

**Comment by radekk** [comment]
We are no longer accepting new accounts on webtask platform. There are plans to add AWS Lambda support in the future. Before it happens, I can suggest using this tool in the command line mode for now.
I will let you know when we release a new version with lambda support.
