### ISSUE TITLE
Allow Typescript (TS/TSX)

### ISSUE THREAD

**Issue by shazm** [auth0/repo-supervisor#39]
I've got support enabled for typescript files for our use case - just wanted some guidance on the best way of submitting a pull request to have this in the main repo :)

I use https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/typescript-estree for finding string tokens, and more or less use the existing JS/JSON filters and it seems to work pretty well.

**Comment by radekk** [comment]
Hi @shazm, it would be great to support TypeScript in our tool. If you would like to help with the implementation I updated a documentation on adding a new file support: https://github.com/auth0/repo-supervisor/blob/master/docs/add.new.file.type.md

Feel free to create a PR and I can guide you from there. Happy to help 👍
