### ISSUE TITLE
Dockerfile missing zip package in version 3.0.0

### ISSUE THREAD

**Issue by eliottthomas1** [auth0/repo-supervisor#41]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

the docker image is missing the Zip package so fails to build at the npm package script. Expect the build to succeed. 

### Reproduction

Pull the latest changes from master and build the docker image.
It will fail at `zip -j ./dist/awslambda.zip ./dist/awslambda.js` 
with the error:
"sh: 1: zip: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! repo-supervisor@3.0.0 package: `zip -j ./dist/awslambda.zip ./dist/awslambda.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the repo-supervisor@3.0.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above."

### Environment

- **Version 3.0.0**

**Comment by radekk** [comment]
We can close this one as it was fixed in #42
