### ISSUE TITLE
Crashes on the presence of a symlink

### ISSUE THREAD

**Issue by glenjamin** [auth0/repo-supervisor#8]
When attempting to run this on a directory which contains symlinks, the process crashes.

This appears to be a result of using `statSync` over `lstatSync`. It's not entirely clear where this happens as the stack trace points to the webpack bundle.

```
> node dist/cli.js ~/my/files
fs.js:953
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/Users/glen/my/files/something/which/is/a/symlink'
    at Object.fs.statSync (fs.js:953:11)
    at /Users/glen/Development/GitHub/repo-supervisor/dist/cli.js:1:7461
    at Array.forEach (native)
    at e (/Users/glen/Development/GitHub/repo-supervisor/dist/cli.js:1:7415)
    at /Users/glen/Development/GitHub/repo-supervisor/dist/cli.js:1:7503
    at Array.forEach (native)
    at e (/Users/glen/Development/GitHub/repo-supervisor/dist/cli.js:1:7415)
    at Object.<anonymous> (/Users/glen/Development/GitHub/repo-supervisor/dist/cli.js:1:7523)
    at t (/Users/glen/Development/GitHub/repo-supervisor/dist/cli.js:1:177)
    at /Users/glen/Development/GitHub/repo-supervisor/dist/cli.js:1:560
```

**Comment by radekk** [comment]
Thanks @glenjamin for reporting this problem.

I tried to reproduce described issue but couldn't get the same results. Can you provide more details like the structure of your directory where symlinks are located? Are there symlinks to symlinks? Have you double checked if file where symlink is pointing to does really exist?

**Comment by radekk** [comment]
I'm closing this issue. I will reopen as fast as I will get more details on that from the submitter.
